In [1]:
import tushare as ts
import pandas as pd
import numpy as np

In [2]:
pro = ts.pro_api()

In [3]:
date = []
for i in range(94):
    temp = ""
    temp += str(2018-(i-1)//4)
    month = str((4-(i-1)%4)*3)
    if month == "6" :
        day = "30"
    elif  month == "9":
        day ="30"
    else:
        day = "31"
    temp += "{:0>2}".format(month)
    temp += day
    date.append(temp)

3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12
9
6
3
12

In [31]:
n = 3037
for p in code_list["ts_code"].tolist()[n:]:
    asset = pro.balancesheet(ts_code=p, start_date='19951201', end_date='20190431', fields='end_date,total_assets')
    ls1 = mother.index.tolist()
    ls2 = asset.end_date.tolist()
    for i in ls1:
        s = ls2.count(i)
        if s>1:
            asset.drop(asset[asset.end_date == i].index.tolist()[0],axis=0,inplace=True)
    asset.index = asset["end_date"].tolist()
    asset.drop("end_date",axis=1,inplace=True)


    fin_data = mother.join(asset).fillna(0)

    bps = pro.fina_indicator(ts_code=p,start_date='19951201', end_date='20190431')
    temp = pd.DataFrame({"bps":bps["bps"].tolist()},index=bps["end_date"].tolist())
    price = pd.read_csv('trade_data/'+p+'.csv',usecols=["trade_date","close"])
    ls = []
    for k in range(len(temp)):

        s = 0.0
        count = 0
        times = 0
        for i in price["trade_date"]:
            if str(i)[:6]==temp.index.tolist()[k][:6]:
                j = temp.index.tolist()[k][:6]
                while j == temp.index.tolist()[k][:6]:
                    s += price["close"][count]
                    times += 1
                    count += 1
                    if count >len(price)-1:
                        break
                    j = str(price["trade_date"][count])[:6]
                break
            count += 1
        if times == 0:
            ls.append(float("inf"))
        else:
            ls.append(s/times)



    temp.bps=ls/temp.bps
    temp.rename(columns={"bps":"pe"})
    fin_data = fin_data.join(temp).fillna(0)

    fin_data.to_csv('fin_data/'+p+'.csv')
    n += 1
    print("{:<11}".format(p),end="  ")
    print("{:<11}".format(n),end="  ")

601700.SH    3038         601717.SH    3039         601718.SH    3040         601727.SH    3041         601766.SH    3042         601777.SH    3043         601788.SH    3044         601789.SH    3045         601798.SH    3046         601799.SH    3047         601800.SH    3048         601801.SH    3049         601808.SH    3050         601811.SH    3051         601818.SH    3052         601828.SH    3053         601838.SH    3054         601857.SH    3055         601858.SH    3056         601866.SH    3057         601869.SH    3058         601872.SH    3059         601877.SH    3060         601878.SH    3061         601880.SH    3062         601881.SH    3063         601882.SH    3064         601886.SH    3065         601888.SH    3066         601890.SH    3067         601898.SH    3068         601899.SH    3069         601900.SH    3070         601901.SH    3071         601908.SH    3072         601918.SH    3073         601919.SH    3074         601928.SH    3075         601929.SH    3076         601933.SH    3077         601939.SH    3078         601949.SH    3079         601952.SH    3080         601958.SH    3081         601965.SH    3082         601966.SH    3083         601968.SH    3084         601969.SH    3085         601985.SH    3086         601988.SH    3087         601989.SH    3088         601990.SH    3089         601991.SH    3090         601992.SH    3091         601996.SH    3092         601997.SH    3093         601998.SH    3094         601999.SH    3095         603000.SH    3096         603001.SH    3097         603002.SH    3098         603003.SH    3099         603005.SH    3100         603006.SH    3101         603007.SH    3102         603008.SH    3103         603009.SH    3104         603010.SH    3105         603011.SH    3106         603012.SH    3107         603013.SH    3108         603015.SH    3109         603016.SH    3110         603017.SH    3111         603018.SH    3112         603019.SH    3113         603020.SH    3114         603021.SH    3115         603022.SH    3116         603023.SH    3117         603025.SH    3118         603026.SH    3119         603027.SH    3120         603028.SH    3121         603029.SH    3122         603030.SH    3123         603031.SH    3124         603032.SH    3125         603033.SH    3126         603035.SH    3127         603036.SH    3128         603037.SH    3129         603038.SH    3130         603039.SH    3131         603040.SH    3132         603041.SH    3133         603042.SH    3134         603043.SH    3135         603045.SH    3136         603050.SH    3137         603055.SH    3138         603056.SH    3139         603058.SH    3140         603059.SH    3141         603060.SH    3142         603063.SH    3143         603066.SH    3144         603067.SH    3145         603069.SH    3146         603076.SH    3147         603077.SH    3148         603078.SH    3149         603079.SH    3150         603080.SH    3151         603081.SH    3152         603083.SH    3153         603085.SH    3154         603086.SH    3155         603088.SH    3156         603089.SH    3157         603090.SH    3158         603096.SH    3159         603098.SH    3160         603099.SH    3161         603100.SH    3162         603101.SH    3163         603103.SH    3164         603105.SH    3165         603106.SH    3166         603108.SH    3167         603110.SH    3168         603111.SH    3169         603113.SH    3170         603116.SH    3171         603117.SH    3172         603118.SH    3173         603123.SH    3174         603126.SH    3175         603127.SH    3176         603128.SH    3177         603129.SH    3178         603131.SH    3179         603133.SH    3180         603136.SH    3181         603138.SH    3182         603139.SH    3183         603156.SH    3184         603157.SH    3185         603158.SH    3186         603159.SH    3187         603160.SH    3188         603161.SH    3189         603165.SH    3190         603166.SH    3191         603167.SH    3192         603168.SH    3193         603169.SH    3194         603177.SH    3195         603178.SH    3196         603179.SH    3197         603180.SH    3198         603181.SH    3199         603183.SH    3200         603185.SH    3201         603186.SH    3202         603187.SH    3203         603188.SH    3204         603189.SH    3205         603192.SH    3206         603196.SH    3207         603197.SH    3208         603198.SH    3209         603199.SH    3210         603200.SH    3211         603203.SH    3212         603208.SH    3213         603214.SH    3214         603218.SH    3215         603220.SH    3216         603222.SH    3217         603223.SH    3218         603225.SH    3219         603226.SH    3220         603227.SH    3221         603228.SH    3222         603229.SH    3223         603232.SH    3224         603233.SH    3225         603238.SH    3226         603239.SH    3227         603258.SH    3228         603259.SH    3229         603260.SH    3230         603266.SH    3231         603268.SH    3232         603269.SH    3233         603277.SH    3234         603278.SH    3235         603283.SH    3236         603286.SH    3237         603288.SH    3238         603289.SH    3239         603297.SH    3240         603298.SH    3241         603299.SH    3242         603300.SH    3243         603301.SH    3244         603303.SH    3245         603305.SH    3246         603306.SH    3247         603308.SH    3248         603309.SH    3249         603311.SH    3250         603313.SH    3251         603315.SH    3252         603316.SH    3253         603318.SH    3254         603319.SH    3255         603320.SH    3256         603321.SH    3257         603322.SH    3258         603323.SH    3259         603326.SH    3260         603328.SH    3261         603329.SH    3262         603330.SH    3263         603331.SH    3264         603333.SH    3265         603335.SH    3266         603336.SH    3267         603337.SH    3268         603338.SH    3269         603339.SH    3270         603345.SH    3271         603348.SH    3272         603355.SH    3273         603356.SH    3274         603357.SH    3275         603358.SH    3276         603359.SH    3277         603360.SH    3278         603363.SH    3279         603365.SH    3280         603366.SH    3281         603367.SH    3282         603368.SH    3283         603369.SH    3284         603377.SH    3285         603378.SH    3286         603380.SH    3287         603383.SH    3288         603385.SH    3289         603386.SH    3290         603387.SH    3291         603388.SH    3292         603389.SH    3293         603393.SH    3294         603396.SH    3295         603398.SH    3296         603399.SH    3297         603416.SH    3298         603421.SH    3299         603429.SH    3300         603444.SH    3301         603456.SH    3302         603458.SH    3303         603466.SH    3304         603477.SH    3305         603486.SH    3306         603488.SH    3307         603496.SH    3308         603499.SH    3309         603500.SH    3310         603501.SH    3311         603505.SH    3312         603506.SH    3313         603507.SH    3314         603508.SH    3315         603515.SH    3316         603516.SH    3317         603517.SH    3318         603518.SH    3319         603519.SH    3320         603520.SH    3321         603527.SH    3322         603528.SH    3323         603533.SH    3324         603535.SH    3325         603536.SH    3326         603538.SH    3327         603555.SH    3328         603556.SH    3329         603557.SH    3330         603558.SH    3331         603559.SH    3332         603566.SH    3333         603567.SH    3334         603568.SH    3335         603569.SH    3336         603577.SH    3337         603578.SH    3338         603579.SH    3339         603580.SH    3340         603583.SH    3341         603585.SH    3342         603586.SH    3343         603587.SH    3344         603588.SH    3345         603589.SH    3346         603590.SH    3347         603595.SH    3348         603596.SH    3349         603598.SH    3350         603599.SH    3351         603600.SH    3352         603601.SH    3353

603602.SH    3354         603603.SH    3355         603605.SH    3356         603606.SH    3357         603607.SH    3358         603608.SH    3359         603609.SH    3360         603611.SH    3361         603612.SH    3362         603615.SH    3363         603616.SH    3364         603617.SH    3365         603618.SH    3366         603619.SH    3367         603626.SH    3368         603628.SH    3369         603629.SH    3370         603630.SH    3371         603633.SH    3372         603636.SH    3373         603637.SH    3374         603638.SH    3375         603639.SH    3376         603648.SH    3377         603650.SH    3378         603655.SH    3379         603656.SH    3380         603657.SH    3381         603658.SH    3382         603659.SH    3383         603660.SH    3384         603661.SH    3385         603663.SH    3386         603665.SH    3387         603666.SH    3388         603667.SH    3389         603668.SH    3390         603669.SH    3391         603676.SH    3392         603677.SH    3393         603678.SH    3394         603679.SH    3395         603680.SH    3396         603683.SH    3397         603685.SH    3398         603686.SH    3399         603688.SH    3400         603689.SH    3401         603690.SH    3402         603693.SH    3403         603696.SH    3404         603698.SH    3405         603699.SH    3406         603701.SH    3407         603703.SH    3408         603706.SH    3409         603707.SH    3410         603708.SH    3411         603709.SH    3412         603711.SH    3413         603712.SH    3414         603713.SH    3415         603716.SH    3416         603717.SH    3417         603718.SH    3418         603721.SH    3419         603722.SH    3420         603725.SH    3421         603726.SH    3422         603727.SH    3423         603728.SH    3424         603729.SH    3425         603730.SH    3426         603733.SH    3427         603737.SH    3428         603738.SH    3429         603757.SH    3430         603758.SH    3431         603766.SH    3432         603767.SH    3433         603768.SH    3434         603773.SH    3435         603776.SH    3436         603777.SH    3437         603778.SH    3438         603779.SH    3439         603787.SH    3440         603788.SH    3441         603789.SH    3442         603790.SH    3443         603797.SH    3444         603798.SH    3445         603799.SH    3446         603800.SH    3447         603801.SH    3448         603803.SH    3449         603806.SH    3450         603808.SH    3451         603809.SH    3452         603810.SH    3453         603811.SH    3454         603813.SH    3455         603816.SH    3456         603817.SH    3457         603818.SH    3458         603819.SH    3459         603822.SH    3460         603823.SH    3461         603825.SH    3462         603826.SH    3463         603828.SH    3464         603829.SH    3465         603833.SH    3466         603838.SH    3467         603839.SH    3468         603843.SH    3469         603848.SH    3470         603855.SH    3471         603856.SH    3472         603858.SH    3473         603859.SH    3474         603860.SH    3475         603861.SH    3476         603866.SH    3477         603868.SH    3478         603869.SH    3479         603871.SH    3480         603876.SH    3481         603877.SH    3482         603878.SH    3483         603879.SH    3484         603880.SH    3485         603881.SH    3486         603882.SH    3487         603883.SH    3488         603885.SH    3489         603886.SH    3490         603887.SH    3491         603888.SH    3492         603889.SH    3493         603890.SH    3494         603895.SH    3495         603896.SH    3496         603897.SH    3497         603898.SH    3498         603899.SH    3499         603900.SH    3500         603901.SH    3501         603903.SH    3502         603906.SH    3503         603908.SH    3504         603909.SH    3505         603912.SH    3506         603916.SH    3507         603917.SH    3508         603918.SH    3509         603919.SH    3510         603920.SH    3511         603922.SH    3512         603926.SH    3513         603928.SH    3514         603929.SH    3515         603933.SH    3516         603936.SH    3517         603937.SH    3518         603938.SH    3519         603939.SH    3520         603955.SH    3521         603958.SH    3522         603959.SH    3523         603960.SH    3524         603963.SH    3525         603966.SH    3526         603968.SH    3527         603969.SH    3528         603970.SH    3529         603976.SH    3530         603977.SH    3531         603978.SH    3532         603979.SH    3533         603980.SH    3534         603985.SH    3535         603986.SH    3536         603987.SH    3537         603988.SH    3538         603989.SH    3539         603990.SH    3540         603991.SH    3541         603993.SH    3542         603996.SH    3543         603997.SH    3544         603998.SH    3545         603999.SH    3546

In [32]:
bps = pro.fina_indicator(ts_code="001914.SZ",start_date='19951201', end_date='20190431')
temp = pd.DataFrame({"bps":bps["bps"].tolist()},index=bps["end_date"].tolist())

In [33]:
temp

             bps
20190331  7.3407
20181231  7.2598
20180930  7.4145
20180630  6.3594
20180331  6.3738
20171231  6.2649
20170930  5.9385
20170630  5.8371
20170331  6.0047
20161231  6.1212
20160930  5.8387
20160630  5.8847
20160331  5.6973
20151231  5.9339
20150930  4.8998
20150630  4.9882
20150331  5.1547
20141231  5.2587
20140930  4.4238
20140630  4.6192
20140331  4.9316
20131231  4.8602
20130930  4.2905
20130630  4.2040
20130331  4.2954
20121231  4.3781
20120930  4.1029
20120630  3.8183
20120331  7.7607
20111231  7.7832
...          ...
20060331  2.7359
20051231  2.6700
20050930  2.3600
20050630  2.3100
20050331  2.3800
20041231  2.3400
20040930  2.2400
20040630  2.2400
20040331  2.2100
20031231  2.1700
20030930  2.0700
20030630  2.0100
20030331  2.0100
20021231  1.9800
20020930  1.9980
20020630  1.8620
20020331  1.8483
20011231  1.8200
20010630  2.9600
20001231  3.1400
20000630  3.2200
19991231  3.1500
19990630  3.4000
19981231  3.3400
19980630  3.5000
19971231  3.4000
19970630  3.5200
19961231  3.3200
19960630  3.3200
19951231  3.2600

[82 rows x 1 columns]